//This file is generated from hipify-src/doc/markdown/CUDA_Device_API_supported_by_HIP.md with the restriction of <CUDA Ver.> <= 11.5 and <HIP Ver.> <= 4.3.0.
//The prefix is selected as DAPI and its corresponding lower case.

#pragma once

#ifdef DAPI_GPU_API_CUDA

#define dapi___all __all
#define dapi___any __any
#define dapi___assert_fail __assert_fail
#define dapi___assertfail __assertfail
#define dapi___ballot __ballot
#define dapi___brev __brev
#define dapi___brevll __brevll
#define dapi___byte_perm __byte_perm
#define dapi___clz __clz
#define dapi___clzll __clzll
#define dapi___cosf __cosf
#define dapi___dadd_rn __dadd_rn
#define dapi___ddiv_rn __ddiv_rn
#define dapi___dmul_rn __dmul_rn
#define dapi___double2float_rd __double2float_rd
#define dapi___double2float_rn __double2float_rn
#define dapi___double2float_ru __double2float_ru
#define dapi___double2float_rz __double2float_rz
#define dapi___double2hiint __double2hiint
#define dapi___double2int_rd __double2int_rd
#define dapi___double2int_rn __double2int_rn
#define dapi___double2int_ru __double2int_ru
#define dapi___double2int_rz __double2int_rz
#define dapi___double2ll_rd __double2ll_rd
#define dapi___double2ll_rn __double2ll_rn
#define dapi___double2ll_ru __double2ll_ru
#define dapi___double2ll_rz __double2ll_rz
#define dapi___double2loint __double2loint
#define dapi___double2uint_rd __double2uint_rd
#define dapi___double2uint_rn __double2uint_rn
#define dapi___double2uint_ru __double2uint_ru
#define dapi___double2uint_rz __double2uint_rz
#define dapi___double2ull_rd __double2ull_rd
#define dapi___double2ull_rn __double2ull_rn
#define dapi___double2ull_ru __double2ull_ru
#define dapi___double2ull_rz __double2ull_rz
#define dapi___double_as_longlong __double_as_longlong
#define dapi___drcp_rn __drcp_rn
#define dapi___dsqrt_rn __dsqrt_rn
#define dapi___dsub_rn __dsub_rn
#define dapi___exp10f __exp10f
#define dapi___expf __expf
#define dapi___fadd_rn __fadd_rn
#define dapi___fdiv_rn __fdiv_rn
#define dapi___fdividef __fdividef
#define dapi___ffs __ffs
#define dapi___ffsll __ffsll
#define dapi___float22half2_rn __float22half2_rn
#define dapi___float2half __float2half
#define dapi___float2half2_rn __float2half2_rn
#define dapi___float2half_rd __float2half_rd
#define dapi___float2half_rn __float2half_rn
#define dapi___float2half_ru __float2half_ru
#define dapi___float2half_rz __float2half_rz
#define dapi___float2int_rd __float2int_rd
#define dapi___float2int_rn __float2int_rn
#define dapi___float2int_ru __float2int_ru
#define dapi___float2int_rz __float2int_rz
#define dapi___float2ll_rd __float2ll_rd
#define dapi___float2ll_rn __float2ll_rn
#define dapi___float2ll_ru __float2ll_ru
#define dapi___float2ll_rz __float2ll_rz
#define dapi___float2uint_rd __float2uint_rd
#define dapi___float2uint_rn __float2uint_rn
#define dapi___float2uint_ru __float2uint_ru
#define dapi___float2uint_rz __float2uint_rz
#define dapi___float2ull_rd __float2ull_rd
#define dapi___float2ull_rn __float2ull_rn
#define dapi___float2ull_ru __float2ull_ru
#define dapi___float2ull_rz __float2ull_rz
#define dapi___float_as_int __float_as_int
#define dapi___float_as_uint __float_as_uint
#define dapi___floats2half2_rn __floats2half2_rn
#define dapi___fma_rn __fma_rn
#define dapi___fmaf_rn __fmaf_rn
#define dapi___fmul_rn __fmul_rn
#define dapi___frcp_rn __frcp_rn
#define dapi___frsqrt_rn __frsqrt_rn
#define dapi___fsqrt_rn __fsqrt_rn
#define dapi___fsub_rn __fsub_rn
#define dapi___h2div __h2div
#define dapi___habs __habs
#define dapi___habs2 __habs2
#define dapi___hadd __hadd
#define dapi___hadd2 __hadd2
#define dapi___hadd2_sat __hadd2_sat
#define dapi___hadd_sat __hadd_sat
#define dapi___half22float2 __half22float2
#define dapi___half2float __half2float
#define dapi___half2half2 __half2half2
#define dapi___half2int_rd __half2int_rd
#define dapi___half2int_rn __half2int_rn
#define dapi___half2int_ru __half2int_ru
#define dapi___half2int_rz __half2int_rz
#define dapi___half2ll_rd __half2ll_rd
#define dapi___half2ll_rn __half2ll_rn
#define dapi___half2ll_ru __half2ll_ru
#define dapi___half2ll_rz __half2ll_rz
#define dapi___half2short_rd __half2short_rd
#define dapi___half2short_rn __half2short_rn
#define dapi___half2short_ru __half2short_ru
#define dapi___half2short_rz __half2short_rz
#define dapi___half2uint_rd __half2uint_rd
#define dapi___half2uint_rn __half2uint_rn
#define dapi___half2uint_ru __half2uint_ru
#define dapi___half2uint_rz __half2uint_rz
#define dapi___half2ull_rd __half2ull_rd
#define dapi___half2ull_rn __half2ull_rn
#define dapi___half2ull_ru __half2ull_ru
#define dapi___half2ull_rz __half2ull_rz
#define dapi___half2ushort_rd __half2ushort_rd
#define dapi___half2ushort_rn __half2ushort_rn
#define dapi___half2ushort_ru __half2ushort_ru
#define dapi___half2ushort_rz __half2ushort_rz
#define dapi___half_as_short __half_as_short
#define dapi___half_as_ushort __half_as_ushort
#define dapi___halves2half2 __halves2half2
#define dapi___hbeq2 __hbeq2
#define dapi___hbequ2 __hbequ2
#define dapi___hbge2 __hbge2
#define dapi___hbgeu2 __hbgeu2
#define dapi___hbgt2 __hbgt2
#define dapi___hbgtu2 __hbgtu2
#define dapi___hble2 __hble2
#define dapi___hbleu2 __hbleu2
#define dapi___hblt2 __hblt2
#define dapi___hbltu2 __hbltu2
#define dapi___hbne2 __hbne2
#define dapi___hbneu2 __hbneu2
#define dapi___hdiv __hdiv
#define dapi___heq __heq
#define dapi___heq2 __heq2
#define dapi___hequ __hequ
#define dapi___hequ2 __hequ2
#define dapi___hfma __hfma
#define dapi___hfma2 __hfma2
#define dapi___hfma2_sat __hfma2_sat
#define dapi___hfma_sat __hfma_sat
#define dapi___hge __hge
#define dapi___hge2 __hge2
#define dapi___hgeu __hgeu
#define dapi___hgeu2 __hgeu2
#define dapi___hgt __hgt
#define dapi___hgt2 __hgt2
#define dapi___hgtu __hgtu
#define dapi___hgtu2 __hgtu2
#define dapi___high2float __high2float
#define dapi___high2half __high2half
#define dapi___high2half2 __high2half2
#define dapi___highs2half2 __highs2half2
#define dapi___hiloint2double __hiloint2double
#define dapi___hisinf __hisinf
#define dapi___hisnan __hisnan
#define dapi___hisnan2 __hisnan2
#define dapi___hle __hle
#define dapi___hle2 __hle2
#define dapi___hleu __hleu
#define dapi___hleu2 __hleu2
#define dapi___hlt __hlt
#define dapi___hlt2 __hlt2
#define dapi___hltu __hltu
#define dapi___hltu2 __hltu2
#define dapi___hmul __hmul
#define dapi___hmul2 __hmul2
#define dapi___hmul2_sat __hmul2_sat
#define dapi___hmul_sat __hmul_sat
#define dapi___hne __hne
#define dapi___hne2 __hne2
#define dapi___hneg __hneg
#define dapi___hneg2 __hneg2
#define dapi___hneu __hneu
#define dapi___hneu2 __hneu2
#define dapi___hsub __hsub
#define dapi___hsub2 __hsub2
#define dapi___hsub2_sat __hsub2_sat
#define dapi___hsub_sat __hsub_sat
#define dapi___int2double_rn __int2double_rn
#define dapi___int2float_rd __int2float_rd
#define dapi___int2float_rn __int2float_rn
#define dapi___int2float_ru __int2float_ru
#define dapi___int2float_rz __int2float_rz
#define dapi___int2half_rd __int2half_rd
#define dapi___int2half_rn __int2half_rn
#define dapi___int2half_ru __int2half_ru
#define dapi___int2half_rz __int2half_rz
#define dapi___int_as_float __int_as_float
#define dapi___ldca __ldca
#define dapi___ldcg __ldcg
#define dapi___ldcs __ldcs
#define dapi___ldg __ldg
#define dapi___ll2double_rd __ll2double_rd
#define dapi___ll2double_rn __ll2double_rn
#define dapi___ll2double_ru __ll2double_ru
#define dapi___ll2double_rz __ll2double_rz
#define dapi___ll2float_rd __ll2float_rd
#define dapi___ll2float_rn __ll2float_rn
#define dapi___ll2float_ru __ll2float_ru
#define dapi___ll2float_rz __ll2float_rz
#define dapi___ll2half_rd __ll2half_rd
#define dapi___ll2half_rn __ll2half_rn
#define dapi___ll2half_ru __ll2half_ru
#define dapi___ll2half_rz __ll2half_rz
#define dapi___log10f __log10f
#define dapi___log2f __log2f
#define dapi___logf __logf
#define dapi___longlong_as_double __longlong_as_double
#define dapi___low2float __low2float
#define dapi___low2half __low2half
#define dapi___low2half2 __low2half2
#define dapi___lowhigh2highlow __lowhigh2highlow
#define dapi___lows2half2 __lows2half2
#define dapi___mul24 __mul24
#define dapi___mul64hi __mul64hi
#define dapi___mulhi __mulhi
#define dapi___popc __popc
#define dapi___popcll __popcll
#define dapi___powf __powf
#define dapi___rhadd __rhadd
#define dapi___sad __sad
#define dapi___saturatef __saturatef
#define dapi___shfl __shfl
#define dapi___shfl_down __shfl_down
#define dapi___shfl_up __shfl_up
#define dapi___shfl_xor __shfl_xor
#define dapi___short2half_rd __short2half_rd
#define dapi___short2half_rn __short2half_rn
#define dapi___short2half_ru __short2half_ru
#define dapi___short2half_rz __short2half_rz
#define dapi___short_as_half __short_as_half
#define dapi___sincosf __sincosf
#define dapi___sinf __sinf
#define dapi___syncthreads __syncthreads
#define dapi___syncthreads_and __syncthreads_and
#define dapi___syncthreads_count __syncthreads_count
#define dapi___syncthreads_or __syncthreads_or
#define dapi___tanf __tanf
#define dapi___threadfence __threadfence
#define dapi___threadfence_block __threadfence_block
#define dapi___threadfence_system __threadfence_system
#define dapi___uhadd __uhadd
#define dapi___uint2double_rn __uint2double_rn
#define dapi___uint2float_rd __uint2float_rd
#define dapi___uint2float_rn __uint2float_rn
#define dapi___uint2float_ru __uint2float_ru
#define dapi___uint2float_rz __uint2float_rz
#define dapi___uint2half_rd __uint2half_rd
#define dapi___uint2half_rn __uint2half_rn
#define dapi___uint2half_ru __uint2half_ru
#define dapi___uint2half_rz __uint2half_rz
#define dapi___uint_as_float __uint_as_float
#define dapi___ull2double_rd __ull2double_rd
#define dapi___ull2double_rn __ull2double_rn
#define dapi___ull2double_ru __ull2double_ru
#define dapi___ull2double_rz __ull2double_rz
#define dapi___ull2float_rd __ull2float_rd
#define dapi___ull2float_rn __ull2float_rn
#define dapi___ull2float_ru __ull2float_ru
#define dapi___ull2float_rz __ull2float_rz
#define dapi___ull2half_rd __ull2half_rd
#define dapi___ull2half_rn __ull2half_rn
#define dapi___ull2half_ru __ull2half_ru
#define dapi___ull2half_rz __ull2half_rz
#define dapi___umul24 __umul24
#define dapi___umul64hi __umul64hi
#define dapi___umulhi __umulhi
#define dapi___urhadd __urhadd
#define dapi___usad __usad
#define dapi___ushort2half_rd __ushort2half_rd
#define dapi___ushort2half_rn __ushort2half_rn
#define dapi___ushort2half_ru __ushort2half_ru
#define dapi___ushort2half_rz __ushort2half_rz
#define dapi___ushort_as_half __ushort_as_half
#define dapi_abs abs
#define dapi_acos acos
#define dapi_acosf acosf
#define dapi_acosh acosh
#define dapi_acoshf acoshf
#define dapi_asin asin
#define dapi_asinf asinf
#define dapi_asinh asinh
#define dapi_asinhf asinhf
#define dapi_atan atan
#define dapi_atan2 atan2
#define dapi_atan2f atan2f
#define dapi_atanf atanf
#define dapi_atanh atanh
#define dapi_atanhf atanhf
#define dapi_atomicAdd atomicAdd
#define dapi_atomicAdd_system atomicAdd_system
#define dapi_atomicAnd atomicAnd
#define dapi_atomicAnd_system atomicAnd_system
#define dapi_atomicCAS atomicCAS
#define dapi_atomicCAS_system atomicCAS_system
#define dapi_atomicDec atomicDec
#define dapi_atomicExch atomicExch
#define dapi_atomicExch_system atomicExch_system
#define dapi_atomicInc atomicInc
#define dapi_atomicMax atomicMax
#define dapi_atomicMax_system atomicMax_system
#define dapi_atomicMin atomicMin
#define dapi_atomicMin_system atomicMin_system
#define dapi_atomicOr atomicOr
#define dapi_atomicOr_system atomicOr_system
#define dapi_atomicSub atomicSub
#define dapi_atomicSub_system atomicSub_system
#define dapi_atomicXor atomicXor
#define dapi_atomicXor_system atomicXor_system
#define dapi_cbrt cbrt
#define dapi_cbrtf cbrtf
#define dapi_ceil ceil
#define dapi_ceilf ceilf
#define dapi_clock clock
#define dapi_clock64 clock64
#define dapi_copysign copysign
#define dapi_copysignf copysignf
#define dapi_cos cos
#define dapi_cosf cosf
#define dapi_cosh cosh
#define dapi_coshf coshf
#define dapi_cospi cospi
#define dapi_cospif cospif
#define dapi_cyl_bessel_i0 cyl_bessel_i0
#define dapi_cyl_bessel_i0f cyl_bessel_i0f
#define dapi_cyl_bessel_i1 cyl_bessel_i1
#define dapi_cyl_bessel_i1f cyl_bessel_i1f
#define dapi_erf erf
#define dapi_erfc erfc
#define dapi_erfcf erfcf
#define dapi_erfcinv erfcinv
#define dapi_erfcinvf erfcinvf
#define dapi_erfcx erfcx
#define dapi_erfcxf erfcxf
#define dapi_erff erff
#define dapi_erfinv erfinv
#define dapi_erfinvf erfinvf
#define dapi_exp exp
#define dapi_exp10 exp10
#define dapi_exp10f exp10f
#define dapi_exp2 exp2
#define dapi_exp2f exp2f
#define dapi_expf expf
#define dapi_expm1 expm1
#define dapi_expm1f expm1f
#define dapi_fabs fabs
#define dapi_fabsf fabsf
#define dapi_fdim fdim
#define dapi_fdimf fdimf
#define dapi_fdividef fdividef
#define dapi_floor floor
#define dapi_floorf floorf
#define dapi_fma fma
#define dapi_fmaf fmaf
#define dapi_fmax fmax
#define dapi_fmaxf fmaxf
#define dapi_fmin fmin
#define dapi_fminf fminf
#define dapi_fmod fmod
#define dapi_fmodf fmodf
#define dapi_frexp frexp
#define dapi_frexpf frexpf
#define dapi_h2ceil h2ceil
#define dapi_h2cos h2cos
#define dapi_h2exp h2exp
#define dapi_h2exp10 h2exp10
#define dapi_h2exp2 h2exp2
#define dapi_h2floor h2floor
#define dapi_h2log h2log
#define dapi_h2log10 h2log10
#define dapi_h2log2 h2log2
#define dapi_h2rcp h2rcp
#define dapi_h2rint h2rint
#define dapi_h2rsqrt h2rsqrt
#define dapi_h2sin h2sin
#define dapi_h2sqrt h2sqrt
#define dapi_h2trunc h2trunc
#define dapi_hceil hceil
#define dapi_hcos hcos
#define dapi_hexp hexp
#define dapi_hexp10 hexp10
#define dapi_hexp2 hexp2
#define dapi_hfloor hfloor
#define dapi_hlog hlog
#define dapi_hlog10 hlog10
#define dapi_hlog2 hlog2
#define dapi_hrcp hrcp
#define dapi_hrint hrint
#define dapi_hrsqrt hrsqrt
#define dapi_hsin hsin
#define dapi_hsqrt hsqrt
#define dapi_htrunc htrunc
#define dapi_hypot hypot
#define dapi_hypotf hypotf
#define dapi_ilogb ilogb
#define dapi_ilogbf ilogbf
#define dapi_isfinite isfinite
#define dapi_isinf isinf
#define dapi_isnan isnan
#define dapi_j0 j0
#define dapi_j0f j0f
#define dapi_j1 j1
#define dapi_j1f j1f
#define dapi_jn jn
#define dapi_jnf jnf
#define dapi_labs labs
#define dapi_ldexp ldexp
#define dapi_ldexpf ldexpf
#define dapi_lgamma lgamma
#define dapi_lgammaf lgammaf
#define dapi_llabs llabs
#define dapi_llrint llrint
#define dapi_llrintf llrintf
#define dapi_llround llround
#define dapi_llroundf llroundf
#define dapi_log log
#define dapi_log10 log10
#define dapi_log10f log10f
#define dapi_log1p log1p
#define dapi_log1pf log1pf
#define dapi_log2 log2
#define dapi_log2f log2f
#define dapi_logb logb
#define dapi_logbf logbf
#define dapi_logf logf
#define dapi_lrint lrint
#define dapi_lrintf lrintf
#define dapi_lround lround
#define dapi_lroundf lroundf
#define dapi_max max
#define dapi_min min
#define dapi_modf modf
#define dapi_modff modff
#define dapi_nan nan
#define dapi_nanf nanf
#define dapi_nearbyint nearbyint
#define dapi_nearbyintf nearbyintf
#define dapi_nextafter nextafter
#define dapi_nextafterf nextafterf
#define dapi_norm norm
#define dapi_norm3d norm3d
#define dapi_norm3df norm3df
#define dapi_norm4d norm4d
#define dapi_norm4df norm4df
#define dapi_normcdf normcdf
#define dapi_normcdff normcdff
#define dapi_normcdfinv normcdfinv
#define dapi_normcdfinvf normcdfinvf
#define dapi_normf normf
#define dapi_pow pow
#define dapi_powf powf
#define dapi_rcbrt rcbrt
#define dapi_rcbrtf rcbrtf
#define dapi_remainder remainder
#define dapi_remainderf remainderf
#define dapi_remquo remquo
#define dapi_remquof remquof
#define dapi_rhypot rhypot
#define dapi_rhypotf rhypotf
#define dapi_rint rint
#define dapi_rintf rintf
#define dapi_rnorm rnorm
#define dapi_rnorm3d rnorm3d
#define dapi_rnorm3df rnorm3df
#define dapi_rnorm4d rnorm4d
#define dapi_rnorm4df rnorm4df
#define dapi_rnormf rnormf
#define dapi_round round
#define dapi_roundf roundf
#define dapi_rsqrt rsqrt
#define dapi_rsqrtf rsqrtf
#define dapi_scalbln scalbln
#define dapi_scalblnf scalblnf
#define dapi_scalbn scalbn
#define dapi_scalbnf scalbnf
#define dapi_signbit signbit
#define dapi_sin sin
#define dapi_sincos sincos
#define dapi_sincosf sincosf
#define dapi_sincospi sincospi
#define dapi_sincospif sincospif
#define dapi_sinf sinf
#define dapi_sinh sinh
#define dapi_sinhf sinhf
#define dapi_sinpi sinpi
#define dapi_sinpif sinpif
#define dapi_sqrt sqrt
#define dapi_sqrtf sqrtf
#define dapi_tan tan
#define dapi_tanf tanf
#define dapi_tanh tanh
#define dapi_tanhf tanhf
#define dapi_tgamma tgamma
#define dapi_tgammaf tgammaf
#define dapi_trunc trunc
#define dapi_truncf truncf
#define dapi_y0 y0
#define dapi_y0f y0f
#define dapi_y1 y1
#define dapi_y1f y1f
#define dapi_yn yn
#define dapi_ynf ynf

#endif //DAPI_GPU_API_CUDA


#ifdef DAPI_GPU_API_HIP

#define dapi___all __all
#define dapi___any __any
#define dapi___assert_fail __assert_fail
#define dapi___assertfail __assertfail
#define dapi___ballot __ballot
#define dapi___brev __brev
#define dapi___brevll __brevll
#define dapi___byte_perm __byte_perm
#define dapi___clz __clz
#define dapi___clzll __clzll
#define dapi___cosf __cosf
#define dapi___dadd_rn __dadd_rn
#define dapi___ddiv_rn __ddiv_rn
#define dapi___dmul_rn __dmul_rn
#define dapi___double2float_rd __double2float_rd
#define dapi___double2float_rn __double2float_rn
#define dapi___double2float_ru __double2float_ru
#define dapi___double2float_rz __double2float_rz
#define dapi___double2hiint __double2hiint
#define dapi___double2int_rd __double2int_rd
#define dapi___double2int_rn __double2int_rn
#define dapi___double2int_ru __double2int_ru
#define dapi___double2int_rz __double2int_rz
#define dapi___double2ll_rd __double2ll_rd
#define dapi___double2ll_rn __double2ll_rn
#define dapi___double2ll_ru __double2ll_ru
#define dapi___double2ll_rz __double2ll_rz
#define dapi___double2loint __double2loint
#define dapi___double2uint_rd __double2uint_rd
#define dapi___double2uint_rn __double2uint_rn
#define dapi___double2uint_ru __double2uint_ru
#define dapi___double2uint_rz __double2uint_rz
#define dapi___double2ull_rd __double2ull_rd
#define dapi___double2ull_rn __double2ull_rn
#define dapi___double2ull_ru __double2ull_ru
#define dapi___double2ull_rz __double2ull_rz
#define dapi___double_as_longlong __double_as_longlong
#define dapi___drcp_rn __drcp_rn
#define dapi___dsqrt_rn __dsqrt_rn
#define dapi___dsub_rn __dsub_rn
#define dapi___exp10f __exp10f
#define dapi___expf __expf
#define dapi___fadd_rn __fadd_rn
#define dapi___fdiv_rn __fdiv_rn
#define dapi___fdividef __fdividef
#define dapi___ffs __ffs
#define dapi___ffsll __ffsll
#define dapi___float22half2_rn __float22half2_rn
#define dapi___float2half __float2half
#define dapi___float2half2_rn __float2half2_rn
#define dapi___float2half_rd __float2half_rd
#define dapi___float2half_rn __float2half_rn
#define dapi___float2half_ru __float2half_ru
#define dapi___float2half_rz __float2half_rz
#define dapi___float2int_rd __float2int_rd
#define dapi___float2int_rn __float2int_rn
#define dapi___float2int_ru __float2int_ru
#define dapi___float2int_rz __float2int_rz
#define dapi___float2ll_rd __float2ll_rd
#define dapi___float2ll_rn __float2ll_rn
#define dapi___float2ll_ru __float2ll_ru
#define dapi___float2ll_rz __float2ll_rz
#define dapi___float2uint_rd __float2uint_rd
#define dapi___float2uint_rn __float2uint_rn
#define dapi___float2uint_ru __float2uint_ru
#define dapi___float2uint_rz __float2uint_rz
#define dapi___float2ull_rd __float2ull_rd
#define dapi___float2ull_rn __float2ull_rn
#define dapi___float2ull_ru __float2ull_ru
#define dapi___float2ull_rz __float2ull_rz
#define dapi___float_as_int __float_as_int
#define dapi___float_as_uint __float_as_uint
#define dapi___floats2half2_rn __floats2half2_rn
#define dapi___fma_rn __fma_rn
#define dapi___fmaf_rn __fmaf_rn
#define dapi___fmul_rn __fmul_rn
#define dapi___frcp_rn __frcp_rn
#define dapi___frsqrt_rn __frsqrt_rn
#define dapi___fsqrt_rn __fsqrt_rn
#define dapi___fsub_rn __fsub_rn
#define dapi___h2div __h2div
#define dapi___habs __habs
#define dapi___habs2 __habs2
#define dapi___hadd __hadd
#define dapi___hadd2 __hadd2
#define dapi___hadd2_sat __hadd2_sat
#define dapi___hadd_sat __hadd_sat
#define dapi___half22float2 __half22float2
#define dapi___half2float __half2float
#define dapi___half2half2 __half2half2
#define dapi___half2int_rd __half2int_rd
#define dapi___half2int_rn __half2int_rn
#define dapi___half2int_ru __half2int_ru
#define dapi___half2int_rz __half2int_rz
#define dapi___half2ll_rd __half2ll_rd
#define dapi___half2ll_rn __half2ll_rn
#define dapi___half2ll_ru __half2ll_ru
#define dapi___half2ll_rz __half2ll_rz
#define dapi___half2short_rd __half2short_rd
#define dapi___half2short_rn __half2short_rn
#define dapi___half2short_ru __half2short_ru
#define dapi___half2short_rz __half2short_rz
#define dapi___half2uint_rd __half2uint_rd
#define dapi___half2uint_rn __half2uint_rn
#define dapi___half2uint_ru __half2uint_ru
#define dapi___half2uint_rz __half2uint_rz
#define dapi___half2ull_rd __half2ull_rd
#define dapi___half2ull_rn __half2ull_rn
#define dapi___half2ull_ru __half2ull_ru
#define dapi___half2ull_rz __half2ull_rz
#define dapi___half2ushort_rd __half2ushort_rd
#define dapi___half2ushort_rn __half2ushort_rn
#define dapi___half2ushort_ru __half2ushort_ru
#define dapi___half2ushort_rz __half2ushort_rz
#define dapi___half_as_short __half_as_short
#define dapi___half_as_ushort __half_as_ushort
#define dapi___halves2half2 __halves2half2
#define dapi___hbeq2 __hbeq2
#define dapi___hbequ2 __hbequ2
#define dapi___hbge2 __hbge2
#define dapi___hbgeu2 __hbgeu2
#define dapi___hbgt2 __hbgt2
#define dapi___hbgtu2 __hbgtu2
#define dapi___hble2 __hble2
#define dapi___hbleu2 __hbleu2
#define dapi___hblt2 __hblt2
#define dapi___hbltu2 __hbltu2
#define dapi___hbne2 __hbne2
#define dapi___hbneu2 __hbneu2
#define dapi___hdiv __hdiv
#define dapi___heq __heq
#define dapi___heq2 __heq2
#define dapi___hequ __hequ
#define dapi___hequ2 __hequ2
#define dapi___hfma __hfma
#define dapi___hfma2 __hfma2
#define dapi___hfma2_sat __hfma2_sat
#define dapi___hfma_sat __hfma_sat
#define dapi___hge __hge
#define dapi___hge2 __hge2
#define dapi___hgeu __hgeu
#define dapi___hgeu2 __hgeu2
#define dapi___hgt __hgt
#define dapi___hgt2 __hgt2
#define dapi___hgtu __hgtu
#define dapi___hgtu2 __hgtu2
#define dapi___high2float __high2float
#define dapi___high2half __high2half
#define dapi___high2half2 __high2half2
#define dapi___highs2half2 __highs2half2
#define dapi___hiloint2double __hiloint2double
#define dapi___hisinf __hisinf
#define dapi___hisnan __hisnan
#define dapi___hisnan2 __hisnan2
#define dapi___hle __hle
#define dapi___hle2 __hle2
#define dapi___hleu __hleu
#define dapi___hleu2 __hleu2
#define dapi___hlt __hlt
#define dapi___hlt2 __hlt2
#define dapi___hltu __hltu
#define dapi___hltu2 __hltu2
#define dapi___hmul __hmul
#define dapi___hmul2 __hmul2
#define dapi___hmul2_sat __hmul2_sat
#define dapi___hmul_sat __hmul_sat
#define dapi___hne __hne
#define dapi___hne2 __hne2
#define dapi___hneg __hneg
#define dapi___hneg2 __hneg2
#define dapi___hneu __hneu
#define dapi___hneu2 __hneu2
#define dapi___hsub __hsub
#define dapi___hsub2 __hsub2
#define dapi___hsub2_sat __hsub2_sat
#define dapi___hsub_sat __hsub_sat
#define dapi___int2double_rn __int2double_rn
#define dapi___int2float_rd __int2float_rd
#define dapi___int2float_rn __int2float_rn
#define dapi___int2float_ru __int2float_ru
#define dapi___int2float_rz __int2float_rz
#define dapi___int2half_rd __int2half_rd
#define dapi___int2half_rn __int2half_rn
#define dapi___int2half_ru __int2half_ru
#define dapi___int2half_rz __int2half_rz
#define dapi___int_as_float __int_as_float
#define dapi___ldca __ldca
#define dapi___ldcg __ldcg
#define dapi___ldcs __ldcs
#define dapi___ldg __ldg
#define dapi___ll2double_rd __ll2double_rd
#define dapi___ll2double_rn __ll2double_rn
#define dapi___ll2double_ru __ll2double_ru
#define dapi___ll2double_rz __ll2double_rz
#define dapi___ll2float_rd __ll2float_rd
#define dapi___ll2float_rn __ll2float_rn
#define dapi___ll2float_ru __ll2float_ru
#define dapi___ll2float_rz __ll2float_rz
#define dapi___ll2half_rd __ll2half_rd
#define dapi___ll2half_rn __ll2half_rn
#define dapi___ll2half_ru __ll2half_ru
#define dapi___ll2half_rz __ll2half_rz
#define dapi___log10f __log10f
#define dapi___log2f __log2f
#define dapi___logf __logf
#define dapi___longlong_as_double __longlong_as_double
#define dapi___low2float __low2float
#define dapi___low2half __low2half
#define dapi___low2half2 __low2half2
#define dapi___lowhigh2highlow __lowhigh2highlow
#define dapi___lows2half2 __lows2half2
#define dapi___mul24 __mul24
#define dapi___mul64hi __mul64hi
#define dapi___mulhi __mulhi
#define dapi___popc __popc
#define dapi___popcll __popcll
#define dapi___powf __powf
#define dapi___rhadd __rhadd
#define dapi___sad __sad
#define dapi___saturatef __saturatef
#define dapi___shfl __shfl
#define dapi___shfl_down __shfl_down
#define dapi___shfl_up __shfl_up
#define dapi___shfl_xor __shfl_xor
#define dapi___short2half_rd __short2half_rd
#define dapi___short2half_rn __short2half_rn
#define dapi___short2half_ru __short2half_ru
#define dapi___short2half_rz __short2half_rz
#define dapi___short_as_half __short_as_half
#define dapi___sincosf __sincosf
#define dapi___sinf __sinf
#define dapi___syncthreads __syncthreads
#define dapi___syncthreads_and __syncthreads_and
#define dapi___syncthreads_count __syncthreads_count
#define dapi___syncthreads_or __syncthreads_or
#define dapi___tanf __tanf
#define dapi___threadfence __threadfence
#define dapi___threadfence_block __threadfence_block
#define dapi___threadfence_system __threadfence_system
#define dapi___uhadd __uhadd
#define dapi___uint2double_rn __uint2double_rn
#define dapi___uint2float_rd __uint2float_rd
#define dapi___uint2float_rn __uint2float_rn
#define dapi___uint2float_ru __uint2float_ru
#define dapi___uint2float_rz __uint2float_rz
#define dapi___uint2half_rd __uint2half_rd
#define dapi___uint2half_rn __uint2half_rn
#define dapi___uint2half_ru __uint2half_ru
#define dapi___uint2half_rz __uint2half_rz
#define dapi___uint_as_float __uint_as_float
#define dapi___ull2double_rd __ull2double_rd
#define dapi___ull2double_rn __ull2double_rn
#define dapi___ull2double_ru __ull2double_ru
#define dapi___ull2double_rz __ull2double_rz
#define dapi___ull2float_rd __ull2float_rd
#define dapi___ull2float_rn __ull2float_rn
#define dapi___ull2float_ru __ull2float_ru
#define dapi___ull2float_rz __ull2float_rz
#define dapi___ull2half_rd __ull2half_rd
#define dapi___ull2half_rn __ull2half_rn
#define dapi___ull2half_ru __ull2half_ru
#define dapi___ull2half_rz __ull2half_rz
#define dapi___umul24 __umul24
#define dapi___umul64hi __umul64hi
#define dapi___umulhi __umulhi
#define dapi___urhadd __urhadd
#define dapi___usad __usad
#define dapi___ushort2half_rd __ushort2half_rd
#define dapi___ushort2half_rn __ushort2half_rn
#define dapi___ushort2half_ru __ushort2half_ru
#define dapi___ushort2half_rz __ushort2half_rz
#define dapi___ushort_as_half __ushort_as_half
#define dapi_abs abs
#define dapi_acos acos
#define dapi_acosf acosf
#define dapi_acosh acosh
#define dapi_acoshf acoshf
#define dapi_asin asin
#define dapi_asinf asinf
#define dapi_asinh asinh
#define dapi_asinhf asinhf
#define dapi_atan atan
#define dapi_atan2 atan2
#define dapi_atan2f atan2f
#define dapi_atanf atanf
#define dapi_atanh atanh
#define dapi_atanhf atanhf
#define dapi_atomicAdd atomicAdd
#define dapi_atomicAdd_system atomicAdd_system
#define dapi_atomicAnd atomicAnd
#define dapi_atomicAnd_system atomicAnd_system
#define dapi_atomicCAS atomicCAS
#define dapi_atomicCAS_system atomicCAS_system
#define dapi_atomicDec atomicDec
#define dapi_atomicExch atomicExch
#define dapi_atomicExch_system atomicExch_system
#define dapi_atomicInc atomicInc
#define dapi_atomicMax atomicMax
#define dapi_atomicMax_system atomicMax_system
#define dapi_atomicMin atomicMin
#define dapi_atomicMin_system atomicMin_system
#define dapi_atomicOr atomicOr
#define dapi_atomicOr_system atomicOr_system
#define dapi_atomicSub atomicSub
#define dapi_atomicSub_system atomicSub_system
#define dapi_atomicXor atomicXor
#define dapi_atomicXor_system atomicXor_system
#define dapi_cbrt cbrt
#define dapi_cbrtf cbrtf
#define dapi_ceil ceil
#define dapi_ceilf ceilf
#define dapi_clock clock
#define dapi_clock64 clock64
#define dapi_copysign copysign
#define dapi_copysignf copysignf
#define dapi_cos cos
#define dapi_cosf cosf
#define dapi_cosh cosh
#define dapi_coshf coshf
#define dapi_cospi cospi
#define dapi_cospif cospif
#define dapi_cyl_bessel_i0 cyl_bessel_i0
#define dapi_cyl_bessel_i0f cyl_bessel_i0f
#define dapi_cyl_bessel_i1 cyl_bessel_i1
#define dapi_cyl_bessel_i1f cyl_bessel_i1f
#define dapi_erf erf
#define dapi_erfc erfc
#define dapi_erfcf erfcf
#define dapi_erfcinv erfcinv
#define dapi_erfcinvf erfcinvf
#define dapi_erfcx erfcx
#define dapi_erfcxf erfcxf
#define dapi_erff erff
#define dapi_erfinv erfinv
#define dapi_erfinvf erfinvf
#define dapi_exp exp
#define dapi_exp10 exp10
#define dapi_exp10f exp10f
#define dapi_exp2 exp2
#define dapi_exp2f exp2f
#define dapi_expf expf
#define dapi_expm1 expm1
#define dapi_expm1f expm1f
#define dapi_fabs fabs
#define dapi_fabsf fabsf
#define dapi_fdim fdim
#define dapi_fdimf fdimf
#define dapi_fdividef fdividef
#define dapi_floor floor
#define dapi_floorf floorf
#define dapi_fma fma
#define dapi_fmaf fmaf
#define dapi_fmax fmax
#define dapi_fmaxf fmaxf
#define dapi_fmin fmin
#define dapi_fminf fminf
#define dapi_fmod fmod
#define dapi_fmodf fmodf
#define dapi_frexp frexp
#define dapi_frexpf frexpf
#define dapi_h2ceil h2ceil
#define dapi_h2cos h2cos
#define dapi_h2exp h2exp
#define dapi_h2exp10 h2exp10
#define dapi_h2exp2 h2exp2
#define dapi_h2floor h2floor
#define dapi_h2log h2log
#define dapi_h2log10 h2log10
#define dapi_h2log2 h2log2
#define dapi_h2rcp h2rcp
#define dapi_h2rint h2rint
#define dapi_h2rsqrt h2rsqrt
#define dapi_h2sin h2sin
#define dapi_h2sqrt h2sqrt
#define dapi_h2trunc h2trunc
#define dapi_hceil hceil
#define dapi_hcos hcos
#define dapi_hexp hexp
#define dapi_hexp10 hexp10
#define dapi_hexp2 hexp2
#define dapi_hfloor hfloor
#define dapi_hlog hlog
#define dapi_hlog10 hlog10
#define dapi_hlog2 hlog2
#define dapi_hrcp hrcp
#define dapi_hrint hrint
#define dapi_hrsqrt hrsqrt
#define dapi_hsin hsin
#define dapi_hsqrt hsqrt
#define dapi_htrunc htrunc
#define dapi_hypot hypot
#define dapi_hypotf hypotf
#define dapi_ilogb ilogb
#define dapi_ilogbf ilogbf
#define dapi_isfinite isfinite
#define dapi_isinf isinf
#define dapi_isnan isnan
#define dapi_j0 j0
#define dapi_j0f j0f
#define dapi_j1 j1
#define dapi_j1f j1f
#define dapi_jn jn
#define dapi_jnf jnf
#define dapi_labs labs
#define dapi_ldexp ldexp
#define dapi_ldexpf ldexpf
#define dapi_lgamma lgamma
#define dapi_lgammaf lgammaf
#define dapi_llabs llabs
#define dapi_llrint llrint
#define dapi_llrintf llrintf
#define dapi_llround llround
#define dapi_llroundf llroundf
#define dapi_log log
#define dapi_log10 log10
#define dapi_log10f log10f
#define dapi_log1p log1p
#define dapi_log1pf log1pf
#define dapi_log2 log2
#define dapi_log2f log2f
#define dapi_logb logb
#define dapi_logbf logbf
#define dapi_logf logf
#define dapi_lrint lrint
#define dapi_lrintf lrintf
#define dapi_lround lround
#define dapi_lroundf lroundf
#define dapi_max max
#define dapi_min min
#define dapi_modf modf
#define dapi_modff modff
#define dapi_nan nan
#define dapi_nanf nanf
#define dapi_nearbyint nearbyint
#define dapi_nearbyintf nearbyintf
#define dapi_nextafter nextafter
#define dapi_nextafterf nextafterf
#define dapi_norm norm
#define dapi_norm3d norm3d
#define dapi_norm3df norm3df
#define dapi_norm4d norm4d
#define dapi_norm4df norm4df
#define dapi_normcdf normcdf
#define dapi_normcdff normcdff
#define dapi_normcdfinv normcdfinv
#define dapi_normcdfinvf normcdfinvf
#define dapi_normf normf
#define dapi_pow pow
#define dapi_powf powf
#define dapi_rcbrt rcbrt
#define dapi_rcbrtf rcbrtf
#define dapi_remainder remainder
#define dapi_remainderf remainderf
#define dapi_remquo remquo
#define dapi_remquof remquof
#define dapi_rhypot rhypot
#define dapi_rhypotf rhypotf
#define dapi_rint rint
#define dapi_rintf rintf
#define dapi_rnorm rnorm
#define dapi_rnorm3d rnorm3d
#define dapi_rnorm3df rnorm3df
#define dapi_rnorm4d rnorm4d
#define dapi_rnorm4df rnorm4df
#define dapi_rnormf rnormf
#define dapi_round round
#define dapi_roundf roundf
#define dapi_rsqrt rsqrt
#define dapi_rsqrtf rsqrtf
#define dapi_scalbln scalbln
#define dapi_scalblnf scalblnf
#define dapi_scalbn scalbn
#define dapi_scalbnf scalbnf
#define dapi_signbit signbit
#define dapi_sin sin
#define dapi_sincos sincos
#define dapi_sincosf sincosf
#define dapi_sincospi sincospi
#define dapi_sincospif sincospif
#define dapi_sinf sinf
#define dapi_sinh sinh
#define dapi_sinhf sinhf
#define dapi_sinpi sinpi
#define dapi_sinpif sinpif
#define dapi_sqrt sqrt
#define dapi_sqrtf sqrtf
#define dapi_tan tan
#define dapi_tanf tanf
#define dapi_tanh tanh
#define dapi_tanhf tanhf
#define dapi_tgamma tgamma
#define dapi_tgammaf tgammaf
#define dapi_trunc trunc
#define dapi_truncf truncf
#define dapi_y0 y0
#define dapi_y0f y0f
#define dapi_y1 y1
#define dapi_y1f y1f
#define dapi_yn yn
#define dapi_ynf ynf

#endif //DAPI_GPU_API_HIP
